### ISSUE TITLE
支持winui2

### ISSUE THREAD

**Issue by qjl1569** [ProjectMile/Mile.Xaml#13]
这有可能吗？

**Comment by MouriNaruto** [comment]
Mile.Xaml 一开始就能和 WinUI 2 实现共存
但这并不符合 Mile.Xaml 的设计目的（开发 Windows 11 风格的轻量级 XAML Islands 应用）

毛利

**Comment by MouriNaruto** [comment]
@qjl1569 

动态依赖项 API 应该可用，但是这是 WASDK 的内容，和完整 WASDK 共存并不是 Mile.Xaml 的设计目的（开发 Windows 11 风格的轻量级 XAML Islands 应用）

需要让系统安装额外依赖不如自包含（以靠谱部署的视角，还有部署体积计算必须得计算额外依赖的安装后体积）

Mile.Xaml 不提供 .NET Core 3.x 目标支持，因为这些版本微软已经结束支持

毛利
