### ISSUE TITLE
报错 “System.Reflection.AssemblyCompanyAttribute”特性重复

### ISSUE THREAD

**Issue by ClearSeve** [ProjectMile/Mile.Xaml#16]
![image](https://github.com/ProjectMile/Mile.Xaml/assets/26833671/c7701aee-6fbf-446c-9b08-8f3ed0a99858)
```
已启动生成...
1>------ 已启动生成: 项目: Mile.Xaml.RefreshPackageVersion, 配置: Debug Any CPU ------
2>------ 已启动生成: 项目: Mile.Xaml.ControlStyleXamlGenerator, 配置: Debug Any CPU ------
3>------ 已启动生成: 项目: Mile.Xaml.Managed, 配置: Debug Any CPU ------
3>C:\Users\ClearSeve\Desktop\Mile.Xaml\Output\Objects\Debug\Mile.Xaml.Managed\AnyCPU\net48\.NETFramework,Version=v4.8.AssemblyAttributes.cs(4,12,4,70): error CS0579: “global::System.Runtime.Versioning.TargetFrameworkAttribute”特性重复
3>C:\Users\ClearSeve\Desktop\Mile.Xaml\Output\Objects\Debug\Mile.Xaml.Managed\AnyCPU\net48\Mile.Xaml.Managed.AssemblyInfo.cs(14,12,14,54): error CS0579: “System.Reflection.AssemblyCompanyAttribute”特性重复
3>C:\Users\ClearSeve\Desktop\Mile.Xaml\Output\Objects\Debug\Mile.Xaml.Managed\AnyCPU\net48\Mile.Xaml.Managed.AssemblyInfo.cs(15,12,15,60): error CS0579: “System.Reflection.AssemblyConfigurationAttribute”特性重复
3>C:\Users\ClearSeve\Desktop\Mile.Xaml\Output\Objects\Debug\Mile.Xaml.Managed\AnyCPU\net48\Mile.Xaml.Managed.AssemblyInfo.cs(16,12,16,56): error CS0579: “System.Reflection.AssemblyCopyrightAttribute”特性重复
3>C:\Users\ClearSeve\Desktop\Mile.Xaml\Output\Objects\Debug\Mile.Xaml.Managed\AnyCPU\net48\Mile.Xaml.Managed.AssemblyInfo.cs(17,12,17,58): error CS0579: “System.Reflection.AssemblyFileVersionAttribute”特性重复
3>C:\Users\ClearSeve\Desktop\Mile.Xaml\Output\Objects\Debug\Mile.Xaml.Managed\AnyCPU\net48\Mile.Xaml.Managed.AssemblyInfo.cs(18,12,18,67): error CS0579: “System.Reflection.AssemblyInformationalVersionAttribute”特性重复
3>C:\Users\ClearSeve\Desktop\Mile.Xaml\Output\Objects\Debug\Mile.Xaml.Managed\AnyCPU\net48\Mile.Xaml.Managed.AssemblyInfo.cs(19,12,19,54): error CS0579: “System.Reflection.AssemblyProductAttribute”特性重复
3>C:\Users\ClearSeve\Desktop\Mile.Xaml\Output\Objects\Debug\Mile.Xaml.Managed\AnyCPU\net48\Mile.Xaml.Managed.AssemblyInfo.cs(20,12,20,52): error CS0579: “System.Reflection.AssemblyTitleAttribute”特性重复
3>C:\Users\ClearSeve\Desktop\Mile.Xaml\Output\Objects\Debug\Mile.Xaml.Managed\AnyCPU\net48\Mile.Xaml.Managed.AssemblyInfo.cs(21,12,21,54): error CS0579: “System.Reflection.AssemblyVersionAttribute”特性重复
3>已完成生成项目“Mile.Xaml.Managed.csproj”的操作 - 失败。
2>C:\Users\ClearSeve\Desktop\Mile.Xaml\Output\Objects\Debug\Mile.Xaml.ControlStyleXamlGenerator\AnyCPU\net7.0\.NETCoreApp,Version=v7.0.AssemblyAttributes.cs(4,12,4,70): error CS0579: “global::System.Runtime.Versioning.TargetFrameworkAttribute”特性重复
2>C:\Users\ClearSeve\Desktop\Mile.Xaml\Output\Objects\Debug\Mile.Xaml.ControlStyleXamlGenerator\AnyCPU\net7.0\Mile.Xaml.ControlStyleXamlGenerator.AssemblyInfo.cs(14,12,14,54): error CS0579: “System.Reflection.AssemblyCompanyAttribute”特性重复
2>C:\Users\ClearSeve\Desktop\Mile.Xaml\Output\Objects\Debug\Mile.Xaml.ControlStyleXamlGenerator\AnyCPU\net7.0\Mile.Xaml.ControlStyleXamlGenerator.AssemblyInfo.cs(15,12,15,60): error CS0579: “System.Reflection.AssemblyConfigurationAttribute”特性重复
2>C:\Users\ClearSeve\Desktop\Mile.Xaml\Output\Objects\Debug\Mile.Xaml.ControlStyleXamlGenerator\AnyCPU\net7.0\Mile.Xaml.ControlStyleXamlGenerator.AssemblyInfo.cs(16,12,16,58): error CS0579: “System.Reflection.AssemblyFileVersionAttribute”特性重复
2>C:\Users\ClearSeve\Desktop\Mile.Xaml\Output\Objects\Debug\Mile.Xaml.ControlStyleXamlGenerator\AnyCPU\net7.0\Mile.Xaml.ControlStyleXamlGenerator.AssemblyInfo.cs(17,12,17,67): error CS0579: “System.Reflection.AssemblyInformationalVersionAttribute”特性重复
2>C:\Users\ClearSeve\Desktop\Mile.Xaml\Output\Objects\Debug\Mile.Xaml.ControlStyleXamlGenerator\AnyCPU\net7.0\Mile.Xaml.ControlStyleXamlGenerator.AssemblyInfo.cs(18,12,18,54): error CS0579: “System.Reflection.AssemblyProductAttribute”特性重复
2>C:\Users\ClearSeve\Desktop\Mile.Xaml\Output\Objects\Debug\Mile.Xaml.ControlStyleXamlGenerator\AnyCPU\net7.0\Mile.Xaml.ControlStyleXamlGenerator.AssemblyInfo.cs(19,12,19,52): error CS0579: “System.Reflection.AssemblyTitleAttribute”特性重复
2>C:\Users\ClearSeve\Desktop\Mile.Xaml\Output\Objects\Debug\Mile.Xaml.ControlStyleXamlGenerator\AnyCPU\net7.0\Mile.Xaml.ControlStyleXamlGenerator.AssemblyInfo.cs(20,12,20,54): error CS0579: “System.Reflection.AssemblyVersionAttribute”特性重复
2>已完成生成项目“Mile.Xaml.ControlStyleXamlGenerator.csproj”的操作 - 失败。
1>C:\Users\ClearSeve\Desktop\Mile.Xaml\Output\Objects\Debug\Mile.Xaml.RefreshPackageVersion\AnyCPU\net7.0\.NETCoreApp,Version=v7.0.AssemblyAttributes.cs(4,12,4,70): error CS0579: “global::System.Runtime.Versioning.TargetFrameworkAttribute”特性重复
1>C:\Users\ClearSeve\Desktop\Mile.Xaml\Output\Objects\Debug\Mile.Xaml.RefreshPackageVersion\AnyCPU\net7.0\Mile.Xaml.RefreshPackageVersion.AssemblyInfo.cs(14,12,14,54): error CS0579: “System.Reflection.AssemblyCompanyAttribute”特性重复
1>C:\Users\ClearSeve\Desktop\Mile.Xaml\Output\Objects\Debug\Mile.Xaml.RefreshPackageVersion\AnyCPU\net7.0\Mile.Xaml.RefreshPackageVersion.AssemblyInfo.cs(15,12,15,60): error CS0579: “System.Reflection.AssemblyConfigurationAttribute”特性重复
1>C:\Users\ClearSeve\Desktop\Mile.Xaml\Output\Objects\Debug\Mile.Xaml.RefreshPackageVersion\AnyCPU\net7.0\Mile.Xaml.RefreshPackageVersion.AssemblyInfo.cs(16,12,16,58): error CS0579: “System.Reflection.AssemblyFileVersionAttribute”特性重复
1>C:\Users\ClearSeve\Desktop\Mile.Xaml\Output\Objects\Debug\Mile.Xaml.RefreshPackageVersion\AnyCPU\net7.0\Mile.Xaml.RefreshPackageVersion.AssemblyInfo.cs(17,12,17,67): error CS0579: “System.Reflection.AssemblyInformationalVersionAttribute”特性重复
1>C:\Users\ClearSeve\Desktop\Mile.Xaml\Output\Objects\Debug\Mile.Xaml.RefreshPackageVersion\AnyCPU\net7.0\Mile.Xaml.RefreshPackageVersion.AssemblyInfo.cs(18,12,18,54): error CS0579: “System.Reflection.AssemblyProductAttribute”特性重复
1>C:\Users\ClearSeve\Desktop\Mile.Xaml\Output\Objects\Debug\Mile.Xaml.RefreshPackageVersion\AnyCPU\net7.0\Mile.Xaml.RefreshPackageVersion.AssemblyInfo.cs(19,12,19,52): error CS0579: “System.Reflection.AssemblyTitleAttribute”特性重复
1>C:\Users\ClearSeve\Desktop\Mile.Xaml\Output\Objects\Debug\Mile.Xaml.RefreshPackageVersion\AnyCPU\net7.0\Mile.Xaml.RefreshPackageVersion.AssemblyInfo.cs(20,12,20,54): error CS0579: “System.Reflection.AssemblyVersionAttribute”特性重复
1>已完成生成项目“Mile.Xaml.RefreshPackageVersion.csproj”的操作 - 失败。
========== 生成: 0 成功，3 失败，2 最新，0 已跳过 ==========
========= 生成 开始于 7:12 PM，并花费了 01.707 秒 ==========
```
这个报错特性重复是什么意思? 怎么解决 拜托了

**Comment by Gaoyifei1011** [comment]
> ![image](https://user-images.githubusercontent.com/26833671/243084957-c7701aee-6fbf-446c-9b08-8f3ed0a99858.png)
> 
> ```
> 已启动生成...
> 1>------ 已启动生成: 项目: Mile.Xaml.RefreshPackageVersion, 配置: Debug Any CPU ------
> 2>------ 已启动生成: 项目: Mile.Xaml.ControlStyleXamlGenerator, 配置: Debug Any CPU ------
> 3>------ 已启动生成: 项目: Mile.Xaml.Managed, 配置: Debug Any CPU ------
> 3>C:\Users\ClearSeve\Desktop\Mile.Xaml\Output\Objects\Debug\Mile.Xaml.Managed\AnyCPU\net48\.NETFramework,Version=v4.8.AssemblyAttributes.cs(4,12,4,70): error CS0579: “global::System.Runtime.Versioning.TargetFrameworkAttribute”特性重复
> 3>C:\Users\ClearSeve\Desktop\Mile.Xaml\Output\Objects\Debug\Mile.Xaml.Managed\AnyCPU\net48\Mile.Xaml.Managed.AssemblyInfo.cs(14,12,14,54): error CS0579: “System.Reflection.AssemblyCompanyAttribute”特性重复
> 3>C:\Users\ClearSeve\Desktop\Mile.Xaml\Output\Objects\Debug\Mile.Xaml.Managed\AnyCPU\net48\Mile.Xaml.Managed.AssemblyInfo.cs(15,12,15,60): error CS0579: “System.Reflection.AssemblyConfigurationAttribute”特性重复
> 3>C:\Users\ClearSeve\Desktop\Mile.Xaml\Output\Objects\Debug\Mile.Xaml.Managed\AnyCPU\net48\Mile.Xaml.Managed.AssemblyInfo.cs(16,12,16,56): error CS0579: “System.Reflection.AssemblyCopyrightAttribute”特性重复
> 3>C:\Users\ClearSeve\Desktop\Mile.Xaml\Output\Objects\Debug\Mile.Xaml.Managed\AnyCPU\net48\Mile.Xaml.Managed.AssemblyInfo.cs(17,12,17,58): error CS0579: “System.Reflection.AssemblyFileVersionAttribute”特性重复
> 3>C:\Users\ClearSeve\Desktop\Mile.Xaml\Output\Objects\Debug\Mile.Xaml.Managed\AnyCPU\net48\Mile.Xaml.Managed.AssemblyInfo.cs(18,12,18,67): error CS0579: “System.Reflection.AssemblyInformationalVersionAttribute”特性重复
> 3>C:\Users\ClearSeve\Desktop\Mile.Xaml\Output\Objects\Debug\Mile.Xaml.Managed\AnyCPU\net48\Mile.Xaml.Managed.AssemblyInfo.cs(19,12,19,54): error CS0579: “System.Reflection.AssemblyProductAttribute”特性重复
> 3>C:\Users\ClearSeve\Desktop\Mile.Xaml\Output\Objects\Debug\Mile.Xaml.Managed\AnyCPU\net48\Mile.Xaml.Managed.AssemblyInfo.cs(20,12,20,52): error CS0579: “System.Reflection.AssemblyTitleAttribute”特性重复
> 3>C:\Users\ClearSeve\Desktop\Mile.Xaml\Output\Objects\Debug\Mile.Xaml.Managed\AnyCPU\net48\Mile.Xaml.Managed.AssemblyInfo.cs(21,12,21,54): error CS0579: “System.Reflection.AssemblyVersionAttribute”特性重复
> 3>已完成生成项目“Mile.Xaml.Managed.csproj”的操作 - 失败。
> 2>C:\Users\ClearSeve\Desktop\Mile.Xaml\Output\Objects\Debug\Mile.Xaml.ControlStyleXamlGenerator\AnyCPU\net7.0\.NETCoreApp,Version=v7.0.AssemblyAttributes.cs(4,12,4,70): error CS0579: “global::System.Runtime.Versioning.TargetFrameworkAttribute”特性重复
> 2>C:\Users\ClearSeve\Desktop\Mile.Xaml\Output\Objects\Debug\Mile.Xaml.ControlStyleXamlGenerator\AnyCPU\net7.0\Mile.Xaml.ControlStyleXamlGenerator.AssemblyInfo.cs(14,12,14,54): error CS0579: “System.Reflection.AssemblyCompanyAttribute”特性重复
> 2>C:\Users\ClearSeve\Desktop\Mile.Xaml\Output\Objects\Debug\Mile.Xaml.ControlStyleXamlGenerator\AnyCPU\net7.0\Mile.Xaml.ControlStyleXamlGenerator.AssemblyInfo.cs(15,12,15,60): error CS0579: “System.Reflection.AssemblyConfigurationAttribute”特性重复
> 2>C:\Users\ClearSeve\Desktop\Mile.Xaml\Output\Objects\Debug\Mile.Xaml.ControlStyleXamlGenerator\AnyCPU\net7.0\Mile.Xaml.ControlStyleXamlGenerator.AssemblyInfo.cs(16,12,16,58): error CS0579: “System.Reflection.AssemblyFileVersionAttribute”特性重复
> 2>C:\Users\ClearSeve\Desktop\Mile.Xaml\Output\Objects\Debug\Mile.Xaml.ControlStyleXamlGenerator\AnyCPU\net7.0\Mile.Xaml.ControlStyleXamlGenerator.AssemblyInfo.cs(17,12,17,67): error CS0579: “System.Reflection.AssemblyInformationalVersionAttribute”特性重复
> 2>C:\Users\ClearSeve\Desktop\Mile.Xaml\Output\Objects\Debug\Mile.Xaml.ControlStyleXamlGenerator\AnyCPU\net7.0\Mile.Xaml.ControlStyleXamlGenerator.AssemblyInfo.cs(18,12,18,54): error CS0579: “System.Reflection.AssemblyProductAttribute”特性重复
> 2>C:\Users\ClearSeve\Desktop\Mile.Xaml\Output\Objects\Debug\Mile.Xaml.ControlStyleXamlGenerator\AnyCPU\net7.0\Mile.Xaml.ControlStyleXamlGenerator.AssemblyInfo.cs(19,12,19,52): error CS0579: “System.Reflection.AssemblyTitleAttribute”特性重复
> 2>C:\Users\ClearSeve\Desktop\Mile.Xaml\Output\Objects\Debug\Mile.Xaml.ControlStyleXamlGenerator\AnyCPU\net7.0\Mile.Xaml.ControlStyleXamlGenerator.AssemblyInfo.cs(20,12,20,54): error CS0579: “System.Reflection.AssemblyVersionAttribute”特性重复
> 2>已完成生成项目“Mile.Xaml.ControlStyleXamlGenerator.csproj”的操作 - 失败。
> 1>C:\Users\ClearSeve\Desktop\Mile.Xaml\Output\Objects\Debug\Mile.Xaml.RefreshPackageVersion\AnyCPU\net7.0\.NETCoreApp,Version=v7.0.AssemblyAttributes.cs(4,12,4,70): error CS0579: “global::System.Runtime.Versioning.TargetFrameworkAttribute”特性重复
> 1>C:\Users\ClearSeve\Desktop\Mile.Xaml\Output\Objects\Debug\Mile.Xaml.RefreshPackageVersion\AnyCPU\net7.0\Mile.Xaml.RefreshPackageVersion.AssemblyInfo.cs(14,12,14,54): error CS0579: “System.Reflection.AssemblyCompanyAttribute”特性重复
> 1>C:\Users\ClearSeve\Desktop\Mile.Xaml\Output\Objects\Debug\Mile.Xaml.RefreshPackageVersion\AnyCPU\net7.0\Mile.Xaml.RefreshPackageVersion.AssemblyInfo.cs(15,12,15,60): error CS0579: “System.Reflection.AssemblyConfigurationAttribute”特性重复
> 1>C:\Users\ClearSeve\Desktop\Mile.Xaml\Output\Objects\Debug\Mile.Xaml.RefreshPackageVersion\AnyCPU\net7.0\Mile.Xaml.RefreshPackageVersion.AssemblyInfo.cs(16,12,16,58): error CS0579: “System.Reflection.AssemblyFileVersionAttribute”特性重复
> 1>C:\Users\ClearSeve\Desktop\Mile.Xaml\Output\Objects\Debug\Mile.Xaml.RefreshPackageVersion\AnyCPU\net7.0\Mile.Xaml.RefreshPackageVersion.AssemblyInfo.cs(17,12,17,67): error CS0579: “System.Reflection.AssemblyInformationalVersionAttribute”特性重复
> 1>C:\Users\ClearSeve\Desktop\Mile.Xaml\Output\Objects\Debug\Mile.Xaml.RefreshPackageVersion\AnyCPU\net7.0\Mile.Xaml.RefreshPackageVersion.AssemblyInfo.cs(18,12,18,54): error CS0579: “System.Reflection.AssemblyProductAttribute”特性重复
> 1>C:\Users\ClearSeve\Desktop\Mile.Xaml\Output\Objects\Debug\Mile.Xaml.RefreshPackageVersion\AnyCPU\net7.0\Mile.Xaml.RefreshPackageVersion.AssemblyInfo.cs(19,12,19,52): error CS0579: “System.Reflection.AssemblyTitleAttribute”特性重复
> 1>C:\Users\ClearSeve\Desktop\Mile.Xaml\Output\Objects\Debug\Mile.Xaml.RefreshPackageVersion\AnyCPU\net7.0\Mile.Xaml.RefreshPackageVersion.AssemblyInfo.cs(20,12,20,54): error CS0579: “System.Reflection.AssemblyVersionAttribute”特性重复
> 1>已完成生成项目“Mile.Xaml.RefreshPackageVersion.csproj”的操作 - 失败。
> ========== 生成: 0 成功，3 失败，2 最新，0 已跳过 ==========
> ========= 生成 开始于 7:12 PM，并花费了 01.707 秒 ==========
> ```
> 
> 这个报错特性重复是什么意思? 怎么解决 拜托了

您可以打开csproj文件，在propertygroup节点下添加一行内容<GenerateAssemblyInfo>false</GenerateAssemblyInfo>，然后再尝试编译一下试试，看是否会报错

**Comment by Gaoyifei1011** [comment]
![Screenshot_2023-06-03-20-01-40-846_com android browser](https://github.com/ProjectMile/Mile.Xaml/assets/49179966/63708bf1-5804-4386-8515-8713e0f6cf61)

**Comment by ClearSeve** [comment]
大意了, 我以为是项目导致的, 没有去百度感谢大佬指点!
