### ISSUE TITLE
使用Mile.xaml时，App.xaml不能修改为其他名称

### ISSUE THREAD

**Issue by Gaoyifei1011** [ProjectMile/Mile.Xaml#5]
在MSIX打包项目中，如果将App.xaml修改为其他名称后，程序将无法编译，但如果不修改，程序的根目录会出现多个编译后的App.xbf文件，如果存在多个项目的情况下时，会发生冲突，希望能解决一下

**Comment by AndromedaMelody** [comment]
这个是.NET SDK的DefaultFileGlobbing功能，自动add items仅可为App.xaml或Application.xaml，其他名称需自行修改相应文件的Build Action为Application definition，故关闭issue
