### ISSUE TITLE
希望能简单的包装一下Window类，让其更简洁易用（类似于WPF）

### ISSUE THREAD

**Issue by Gaoyifei1011** [ProjectMile/Mile.Xaml#6]
![image](https://user-images.githubusercontent.com/49179966/221406847-791bf0d9-a1c2-4d7f-bd1f-e538770b45a5.png)
如图所示，针对Mile.xaml.samples(.net framework)下，我对Window类做了一个简单的包装，可以让其像Winui3一样通过实例化window对象并通过Activate方法来激活窗口

Window类代码

    public class NewWindow
    {
        public const int CreateUseDefault = unchecked((int)0x80000000);

        public string Title { get; set; } = string.Empty;

        public IntPtr Handle { get; set; } = IntPtr.Zero;

        public object Content { get; set; } = new object();

        private STARTUPINFO StartupInfo = new STARTUPINFO();

        public NewWindow()
        {
            Handle = User32Library.CreateWindowEx(
                WindowStylesEx.WS_EX_LEFT,
                "Mile.Xaml.ContentWindow",
                "获取商店应用 辅助程序",
                WindowStyles.WS_OVERLAPPEDWINDOW,
                CreateUseDefault,
                0,
                CreateUseDefault,
                0,
                IntPtr.Zero,
                IntPtr.Zero,
                Kernel32Library.GetModuleHandleW(null),
                Marshal.GetIUnknownForObject(new MainPage())
                );

            if (Handle == IntPtr.Zero)
            {
                throw new ApplicationException("初始化窗口失败");
            }
        }

        public void Activate()
        {
            StartupInfo.cb = Marshal.SizeOf(StartupInfo);
            Kernel32Library.GetStartupInfoW(out StartupInfo);

            User32Library.ShowWindow(Handle, StartupInfo.wShowWindow);
            User32Library.UpdateWindow(Handle);

            while (User32Library.GetMessage(out MSG msg, IntPtr.Zero, WindowMessage.WM_NULL, WindowMessage.WM_NULL))
            {
                if (msg.message == WindowMessage.WM_SYSKEYDOWN && msg.wParam == (IntPtr)VirtualKey.VK_F4)
                {
                    User32Library.SendMessage(User32Library.GetAncestor(Handle, GetAncestorFlags.GA_ROOT), msg.message, msg.wParam, msg.lParam);
                    continue;
                }

                User32Library.TranslateMessage(ref msg);
                User32Library.DispatchMessage(ref msg);
            }
        }
    }

SingleInstanceApp类的代码（用来启动单实例应用，参考了一下WPF使用WindowsFormsAppliacationBase创建单实例程序）

    public class SingleInstanceApp : WindowsFormsApplicationBase, IDisposable
    {
        private bool isDisposed = false;

        private App ApplicationRoot { get; set; }

        public IntPtr WindowHandle { get; set; }

        public SingleInstanceApp()
        {
            IsSingleInstance = true;
        }

        protected override bool OnStartup(StartupEventArgs eventArgs)
        {
            ApplicationRoot = new App();
            return base.OnStartup(eventArgs);
        }

        protected override void OnRun()
        {
            base.OnRun();
            NewWindow Window = new NewWindow();
            Window.Activate();
        }

        protected override void OnStartupNextInstance(StartupNextInstanceEventArgs args)
        {
            User32Library.SetForegroundWindow(WindowHandle);
            base.OnStartupNextInstance(args);
        }

        protected override void OnShutdown()
        {
            base.OnShutdown();
            Dispose();
        }

        public void Dispose()
        {
            Dispose(true);
            GC.SuppressFinalize(this);
        }

        ~SingleInstanceApp()
        {
            Dispose(false);
        }

        /// <summary>
        /// 释放资源
        /// </summary>
        protected virtual void Dispose(bool disposing)
        {
            if (isDisposed) return;
            if (disposing && ApplicationRoot is not null)
            {
                ApplicationRoot.Dispose();
            }
            isDisposed = true;
        }
    }

**Comment by AndromedaMelody** [comment]
a6fe0b306e0885efb4e5c7b51a60b7f7b129e790...a060acc3ac26bf5f8e872adc668fd5296a577f68
