### ISSUE TITLE
拖动窗口大小时，内容对话框及其烟雾背景大小和位置不会变化

### ISSUE THREAD

**Issue by Gaoyifei1011** [ProjectMile/Mile.Xaml#7]
![EYZDO8E64T4~QL68BNZ0V}I](https://user-images.githubusercontent.com/49179966/221523989-c0aa654f-5261-43d7-baed-a08d6a9010a8.jpg)
如图所示，当窗口大小发生改变时，内容对话框及其烟雾背景的位置和覆盖面应该发生变化，但实际上并没有

**Comment by MouriNaruto** [comment]
Content Dialog 这个属于 XAML Islands 的已知问题

Terminal 等使用 XAML Islands 的 App，用到这个设施的时候都会想方设法不让用户变更窗口大小或者让用户变更窗口大小的时候 Content Dialog 自动消失

这也是 Mile.Xaml 要搞 Content Window 的重要原因之一

毛利

**Comment by AndromedaMelody** [comment]
8d7a26c741ba8ed1e735e228f720bd3d8f054355
